# Generated by Django 2.2.7 on 2019-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='repo_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='repo',
            name='login',
            field=models.CharField(max_length=255),
        ),
    ]
