# Generated by Django 2.2.7 on 2019-11-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20191121_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repo',
            name='stargazer',
            field=models.IntegerField(default=0),
        ),
    ]
