# Generated by Django 2.2.7 on 2019-11-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20191121_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lang',
            old_name='repo_name',
            new_name='repo',
        ),
        migrations.RenameField(
            model_name='repo',
            old_name='login',
            new_name='username',
        ),
    ]
